version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    app:
      image: axelclark/docker_phx:0.1.0
      env_file:
        - config/docker.env
      ports:
        - "4000:4000"
      depends_on:
        - db
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
    db:
      image: postgres:10-alpine
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      volumes:
        - "./volumes/postgres:/var/lib/postgresql/data"
      ports:
        - "5432:5432"
      env_file:
        - config/docker.env
  
  volumes:
    nginx_secrets: 
