# File docker_phx/docker-compose.yml
version: "3.5"


networks:
  webnet:
    driver: overlay
    attachable: true # Needed in order to run custom commands in the container

services:

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      STAGING: ${STAGING}
      DHPARAM_SIZE: ${DHPARAM_SIZE}
      RSA_KEY_SIZE: ${RSA_KEY_SIZE}
      ELLIPTIC_CURVE: ${ELLIPTIC_CURVE}
      USE_ECDSA: ${USE_ECDSA}
      RENEWAL_INTERVAL: ${RENEWAL_INTERVAL}
      DEBUG: ${DEBUG}
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    networks: 
      - webnet
    network_mode: "host"

  app:
    image: axelclark/docker_phx:0.1.0
    env_file:
      - config/docker.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  db:
    image: postgres:10-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - config/docker.env
    networks:
      - webnet

volumes:
  nginx_secrets: